services:
    nginx:
        image: nginx:latest
        restart: no
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8876:3476"
        depends_on:
            - app
        healthcheck:
          test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
          interval: 10s
          timeout: 3s
          retries: 3
          start_period: 5s
        container_name: tracker-nginx

    app:
        restart: no
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
            network: host
        volumes:
            - ./:/var/www
        depends_on:
            postgres:
                condition: service_healthy
        container_name: tracker-app

    postgres:
        image: postgres:latest
        restart: unless-stopped
        volumes:
            - ./tmp/db:/var/lib/postgresql
        environment:
            POSTGRES_DB: tracker_db
            POSTGRES_USER: root
            POSTGRES_PASSWORD: sailenser
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
            interval: 5s
            timeout: 3s
            retries: 10
            start_period: 10s
        container_name: tracker-db
